version: 2.1

orbs:
  vsce: uraway/vsce@0.0.1

jobs:
  test:
    executor: vsce/node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-cache-{{ .Branch }}
            - v1-node-cache-
      - run: yarn install
      - save_cache:
          key: v1-node-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn test

workflows:
  test-publish:
    jobs:
      - test
      - vsce/publish:
          publish-token-variable: VSCODE_MARKETPLACE_TOKEN
          push-git-tag: true
          ssh-fingerprints: 69:b1:99:a9:aa:ba:93:a0:e2:1f:62:a4:c2:63:c2:c5
          prefer-yarn: true
          pre-install-steps:
            - restore_cache:
                keys:
                  - v1-node-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
                  - v1-node-cache-{{ .Branch }}
                  - v1-node-cache-
          post-install-steps:
            - save_cache:
                key: v1-node-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
                paths:
                  - node_modules
          requires:
            - test
          filters:
            branches:
              only: master
