version: 2.1

orbs:
  vsce: uraway/vsce@0.0.4

jobs:
  test:
    executor: vsce/node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-cache-{{ .Branch }}
            - v1-node-cache-
      - run: yarn install
      - save_cache:
          key: v1-node-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn lint
      - run: sudo apt update && sudo apt install libxss1 xvfb
      - run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          yarn ui-test

workflows:
  test-publish:
    jobs:
      - test
      - vsce/publish:
          publish-token-variable: VSCODE_MARKETPLACE_TOKEN
          push-git-tag: true
          ssh-fingerprints: ef:72:f6:8f:46:fd:07:41:70:d7:a4:98:63:05:fa:89
          prefer-yarn: true
          pre-install-steps:
            - restore_cache:
                keys:
                  - v1-node-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
                  - v1-node-cache-{{ .Branch }}
                  - v1-node-cache-
          post-install-steps:
            - save_cache:
                key: v1-node-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
                paths:
                  - node_modules
          requires:
            - test
          filters:
            branches:
              only: master
